parameters:
  buildType: 'Debug'
  generator: 'Visual Studio 16 2019'
  cmakeArgs: ''
  sourceDir: '$(System.DefaultWorkingDirectory)'

steps:

  - script: mkdir  $(System.DefaultWorkingDirectory)\\vulkan_sdk
    displayName: 'Make Vulkan SDK dir'
  - task: CacheBeta@0
    displayName: Cache Vulkan SDK
    inputs:
      key: vulkan_sdk | $(VULKAN_SDK_VERSION)
      path: $(System.DefaultWorkingDirectory)\\vulkan_sdk\\$(VULKAN_SDK_VERSION)
      cacheHitVar: CACHE_RESTORED

  - powershell:  ./.azure-pipelines/install_vulkan.ps1
    displayName: Install Vulkan SDK
    workingDirectory: '${{ parameters.sourceDir }}'
    condition: ne(variables.CACHE_RESTORED, 'true')

  - script: mkdir build
    displayName: 'Create build directory'
    workingDirectory: '${{ parameters.sourceDir }}'

  - script: 'cmake .. -G "${{ parameters.generator }}" ${{ parameters.cmakeArgs }}  -DCMAKE_INSTALL_PREFIX=${{ parameters.sourceDir }}/install'
    displayName: 'Generate build system'
    workingDirectory: '${{ parameters.sourceDir }}/build'
  # - script: cmake " .. 
  #   workingDirectory: build
  #   displayName: 'Generate build system'

  - task: MSBuild@1
    displayName: Build all targets
    inputs:
      solution: '${{ parameters.sourceDir }}/build/ALL_BUILD.vcxproj'
      maximumCpuCount: true
      configuration: ${{ parameters.buildType }}

  - task: MSBuild@1
    displayName: Install build
    inputs:
      solution: '${{ parameters.sourceDir }}/build/INSTALL.vcxproj'
      maximumCpuCount: true
      configuration: ${{ parameters.buildType }}
