parameters:
  buildType: 'Debug'
  generator: 'Visual Studio 16 2019'
  cmakeArgs: ''
  sourceDir: '$(System.DefaultWorkingDirectory)'

steps:
  - script: mkdir build
    displayName: 'Create build directory'
    workingDirectory: '${{ parameters.sourceDir }}'
  - script: 'cmake .. -G "${{ parameters.generator }}" ${{ parameters.cmakeArgs }}  -DCMAKE_INSTALL_PREFIX=${{ parameters.sourceDir }}/install'
    displayName: 'Generate build system'
    workingDirectory: '${{ parameters.sourceDir }}/build' # Optional
  # - script: cmake " .. 
  #   workingDirectory: build
  #   displayName: 'Generate build system'
  - script: cmake --build . --config ${{ parameters.buildType }}
    workingDirectory: ${{ parameters.sourceDir }}/build
    displayName: 'Compile'
  - script: cmake --build . --config ${{ parameters.buildType }} --target INSTALL
    workingDirectory: ${{ parameters.sourceDir }}/build
    displayName: 'Install'
